server:
  port:  8002



spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.168.154:3306/clouddb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: clouddb
    password: 228913

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wang.springcloud.entities

eureka:
  client:
#    是否将自己注册进入EurekaServer
    register-with-eureka: true
#    是否从EurekaServer抓取已经注册的信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka,https://localhost:7001/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true